spring.application.name=Cheminova
server.port=9215

ai.server.url=https://adarsh-singh-01-cheminova-ai.hf.space

spring.datasource.url=jdbc:postgresql://localhost:5432/CheminovaDB
spring.datasource.username=postgres
spring.datasource.password=Zunaid@70
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
